### Sign-up

POST http://localhost:3011/api/addUser/
content-type: application/json

{
  "firstName" : "Samuel",
  "surname" : "Pudinyane",
  "email" : "sam@gmail.com",
  "username" : "sam",
  "password" : "1234",
  "userType" : "admin",
  "phoneNumber" : "027363445"
}

###
POST http://localhost:3011/api/registerNames/
content-type: application/json

{
  "username":"xolani"
}

### Login

POST http://localhost:3011/api/login/
content-type: application/json

{
  "username" : "sabeehah",
  "password" : "sabeehah"
}

###  Get attendees 

GET http://localhost:3011/api/getAttendees/

### Submit register

POST http://localhost:3011/api/submitRegister/
content-type: application/json

{
  "registerName" : "English",
  "selectedAttendees" : ["sabeehah","sabelo"],
  "storedUsername" : "sam"
}

###  Get registers 

POST http://localhost:3011/api/getRegisters/
content-type: application/json

{
  "storedUsername" : "sam"
}

### Delete register
//it works fine no changes needed
POST http://localhost:3011/api/deleteRegister/
content-type: application/json

{
  "registerId" : "1",
  "username":"sam"
}

### View attendance
//modify view register end point
POST http://localhost:3011/api/viewRegister/
content-type: application/json

{
  "registerId" : 1
}

### View specific attendance

POST http://localhost:3011/api/viewSpecificRegister/
content-type: application/json

{
  "registerId":"1",
  "username" : "sabelo",
  "registerName":"Sesotho"
}

### View attendance
//this method works fine no changes needed
POST http://localhost:3011/api/viewRegisterName/
content-type: application/json

{
  "registerId" : 2,
  "username":"sam"
}


### Add attendance

POST http://localhost:3011/api/addAttendance/
content-type: application/json
//this method works no changes needed

{
  "selectedRegisterName": "Sesotho",
  "username": "sabeehah",
  "checkInDate":"2023/10/05"
}

###
POST http://localhost:3011/api/registerNames/
content-type: application/json
//no changes needed
{
  "username":"sabelo"
}

###encrypt
POST http://localhost:3011/api/addUser/
content-type:application/json

{
  "password":"malvapudding"
}

###
POST http://localhost:3011/api/suggest
Content-Type: 

{
  "query":["xol"]
}